"""Add edited_date to Note

Revision ID: 028efc8ced00
Revises: b0bd6662c91b
Create Date: 2026-04-02 19:37:50.560598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028efc8ced00'
down_revision = 'b0bd6662c91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_date', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('edited_date')

    # ### end Alembic commands ###
