"""Add delete and edit fields to DirectMessage

Revision ID: ec1663437891
Revises: 028efc8ced00
Create Date: 2026-04-02 19:45:27.998080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1663437891'
down_revision = '028efc8ced00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('edited_date', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.drop_column('edited_date')
        batch_op.drop_column('edited')
        batch_op.drop_column('deleted_date')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
